<a href="https://colab.research.google.com/github/premreddypagadala/neural-networks/blob/main/Week2/ICP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
class Employee:
    # Class variable to count the number of Employees
    employee_count = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    @staticmethod
    def calculate_average_salary(employee_list):
        total_salary = sum(employee.salary for employee in employee_list)
        return total_salary / len(employee_list) if employee_list else 0

class FulltimeEmployee(Employee):
    pass

# Creating instances
employee1 = Employee("Sumith", "Sumith Family", 30000, "Information Tech")
employee2 = Employee("Naveed", "Naveed Family", 45000, "Marketing Tech")
fulltime_employee1 = FulltimeEmployee("Prem Reddy", "Prem Family", 60000, "Engineering")
fulltime_employee2 = FulltimeEmployee("Manikanta Konda", "Konda Family", 75000, "Engineering")

# List of employees
employee_list = [employee1, employee2, fulltime_employee1, fulltime_employee2]

# Output results
print(f"Total number of employees: {Employee.employee_count}")
print(f"Average salary of employees: {Employee.calculate_average_salary(employee_list):.2f}")


Total number of employees: 4
Average salary of employees: 52500.00


https://drive.google.com/drive/folders/1h1ypSdf1nLmhvocDzBbm1dgjjs7u9yaa?usp=sharing

In [10]:
import numpy as np

# Step 1: Generate a random array of size 20 with floats in the range 1 to 20
random_array = np.random.rand(20) * 19 + 1

# Step 2: Reshape the array to a 4x5 matrix
matrix = random_array.reshape(4, 5)

# Step 3: Replace the maximum value in each row with 0 using broadcasting
row_max = matrix.max(axis=1, keepdims=True)
modified_matrix = np.where(matrix == row_max, 0, matrix)

# Outputs
print("Original 4x5 matrix:\n", matrix)
print("Matrix after replacing max in each row with 0:\n", modified_matrix)


Original 4x5 matrix:
 [[17.11602707 11.82409631 11.42341849 11.15626883 16.74503882]
 [ 6.03569066  6.07705994  3.9509882  15.1693517   1.72656791]
 [15.24419016 15.57290398 10.74342117  6.95279337 19.10124058]
 [14.9682047  16.37141047 12.00610519  6.40387266 16.62854763]]
Matrix after replacing max in each row with 0:
 [[ 0.         11.82409631 11.42341849 11.15626883 16.74503882]
 [ 6.03569066  6.07705994  3.9509882   0.          1.72656791]
 [15.24419016 15.57290398 10.74342117  6.95279337  0.        ]
 [14.9682047  16.37141047 12.00610519  6.40387266  0.        ]]


https://drive.google.com/drive/folders/1h1ypSdf1nLmhvocDzBbm1dgjjs7u9yaa?usp=sharing